version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    working_dir: /var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
    depends_on:
      - redis

  nginx:
    image: nginx:stable
    container_name: nginx_laravel
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - laravel
      
  websocket:
    image: node:20-alpine
    container_name: websocket_server
    working_dir: /usr/src/app
    volumes:
      - ./ws-server:/usr/src/app   # monta código Node
    command: ["node", "server.js"]
    environment:
      - REDIS_HOST=redis           # nombre del servicio Redis interno
      - REDIS_PORT=6379
      # Si necesitas password: REDIS_PASSWORD=******
    ports:
      - "6001:6001"                # puerto público WebSocket
    depends_on:
      - redis
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
